= Greek Names in Software Projects

This is a repo aimed to keep a list of all the different kinds of software projects whose names have a Greek origin. 

== History

The motivation for this came up from the http://www.jhug.gr/[Greek Java User Group] Slack group, where we've been having fun spotting all these software projects in the wild. At some point, I felt it'd be nice to start keeping track... 

== The List


=== Boskos

* Site: https://github.com/kubernetes/test-infra/tree/master/boskos
* Description: Boskos is a resource manager service, that handles and manages different kind of resources and transition between different states.
* What it means: Boskos is a sheperd :sheep: in Greek


=== Istio 

* Site: https://github.com/istio/istio
* Description: Connect, secure, control, and observe services. https://istio.io
* What it means: Istio is the sail of a sailing boat/vessel.


=== Omada 

* Site: https://www.tp-link.com/en/omada-sdn/
* Description: Omada’s Software Defined Networking (SDN) platform integrates network devices providing 100% centralized cloud management.
* What it means: Greek word for "team". A group of people with the same goal.


=== Kallithea 

* Site: https://kallithea-scm.org/
* Description: Kallithea, a free software source code management system supporting two leading version control systems, Mercurial and Git.
* What it means: Usually a name given to areas with a nice view, as it literally translates to good ("kalli") view ("thea")

=== Kiali

* Site: https://www.kiali.io/
* Description: Kiali is an observability console for Istio with service mesh configuration capabilities. 
* What it means: Imagine you're holding a pair of binoculars and a car horn suddenly goes off behind you. Yes, you've dropped the binoculars. They're broken in half. Each half is a "kiali". Also, a binocular - but who has "a" binocular these days?

=== Kubernetes 

* Site: https://kubernetes.io/
* Description: Production-Grade Container Scheduling and Management
* What it means: https://en.wikipedia.org/wiki/Kubernetes[Kubernetes (κυβερνήτης, Greek for "governor", "helmsman" or "captain")]

=== Paketo 

* Site: https://paketo.io
* Description: Modular Buildpacks, written in Go. Paketo Buildpacks provide language runtime support for applications. They leverage the Cloud Native Buildpacks framework to make image builds easy, performant, and secure.
* What it means: Paketo means "package". 


=== Portieris 

* Site: https://github.com/IBM/portieris
* Description: A Kubernetes Admission Controller for verifying image trust with Notary.
* What it means: Portieris is the bouncer you'd find in a club. 


=== Prometheus 

* Site: https://github.com/prometheus/prometheus
* Description: The Prometheus monitoring system and time series database. https://prometheus.io/
* What it means: A name from Greek Mythology, of a Titan, who stole the fire from the gods and gave it to humanity. https://en.wikipedia.org/wiki/Prometheus

=== Synnefo 

* Site: https://www.synnefo.org/
* Description: Synnefo is open source cloud software used to create massively scalable IaaS clouds.
* What it means: Synnefo means "cloud".

=== Scylla 

* Site: https://www.scylladb.com/
* Description: Scylla is a drop-in Apache Cassandra alternative big data database with ultra-low latency and extremely high throughput.
* What it means: Legendary monster who lives on one side of a narrow channel of water, opposite her counterpart Charybdis.


