= Greek Names in Software Projects

This is a repo aimed to keep a list of all the different kinds of software projects whose names have a Greek origin.

== History

The motivation for this came up from the http://www.jhug.gr/[Greek Java User Group] Slack group, where we've been having fun spotting all these software projects in the wild. At some point, I felt it'd be nice to start keeping track...

== The List

=== Apollo

* Site: https://www.apollographql.com
* Description: Apollo is the industry-standard GraphQL implementation, providing the data graph layer that connects modern apps to the cloud.
* What it means: Apollo is one of the Olympian deities in classical Greek and Roman religion and Greek and Roman mythology.

=== Android

* Site: https://www.android.com/
* Description: Android is a mobile operating system based on a modified version of the Linux kernel, designed primarily for touchscreen mobile devices
* What it means: Android is coined from the Greek root andr-, "man" (male) and the suffix -oid, "having the form or likeness of".


=== Boskos

* Site: https://github.com/kubernetes/test-infra/tree/master/boskos
* Description: Boskos is a resource manager service, that handles and manages different kind of resources and transition between different states.
* What it means: Boskos is a sheperd :sheep: in Greek

=== Cassandra 

* Site: https://cassandra.apache.org/
* Description: Cassandra is a highly scalable and available distributed database.
* What it means: Priestess of Apollo in Greek mythology cursed to utter true prophecies, but never to be believed.

=== Exousia 

* Site: https://github.com/eclipse-ee4j/exousia
* Description: Exousia is a standalone implementation of [Jakarta Authorization](https://jakarta.ee/specifications/authorization/2.0/authorization-spec-2.0).
* What it means: authority, power

=== Istio 

* Site: https://github.com/istio/istio
* Description: Connect, secure, control, and observe services. https://istio.io
* What it means: Istio is the sail of a sailing boat/vessel.


=== Omada 

* Site: https://www.tp-link.com/en/omada-sdn/
* Description: Omada’s Software Defined Networking (SDN) platform integrates network devices providing 100% centralized cloud management.
* What it means: Greek word for "team". A group of people with the same goal.


=== Kallithea 

* Site: https://kallithea-scm.org/
* Description: Kallithea, a free software source code management system supporting two leading version control systems, Mercurial and Git.
* What it means: Usually a name given to areas with a nice view, as it literally translates to good ("kalli") view ("thea")

=== Kiali

* Site: https://www.kiali.io/
* Description: Kiali is an observability console for Istio with service mesh configuration capabilities.
* What it means: Imagine you're holding a pair of binoculars and a car horn suddenly goes off behind you. Yes, you've dropped the binoculars. They're broken in half. Each half is a "kiali". Also, a binocular - but who has "a" binocular these days?

=== Kubernetes

* Site: https://kubernetes.io/
* Description: Production-Grade Container Scheduling and Management
* What it means: https://en.wikipedia.org/wiki/Kubernetes[Kubernetes (κυβερνήτης, Greek for "governor", "helmsman" or "captain")]

=== Paketo

* Site: https://paketo.io
* Description: Modular Buildpacks, written in Go. Paketo Buildpacks provide language runtime support for applications. They leverage the Cloud Native Buildpacks framework to make image builds easy, performant, and secure.
* What it means: Paketo means "package".


=== Portieris

* Site: https://github.com/IBM/portieris
* Description: A Kubernetes Admission Controller for verifying image trust with Notary.
* What it means: Portieris is the bouncer you'd find in a club.


=== Prometheus

* Site: https://github.com/prometheus/prometheus
* Description: The Prometheus monitoring system and time series database. https://prometheus.io/
* What it means: A name from Greek Mythology, of a Titan, who stole the fire from the gods and gave it to humanity. https://en.wikipedia.org/wiki/Prometheus

=== Synnefo

* Site: https://www.synnefo.org/
* Description: Synnefo is open source cloud software used to create massively scalable IaaS clouds.
* What it means: Synnefo means "cloud".

=== Scylla

* Site: https://www.scylladb.com/
* Description: Scylla is a drop-in Apache Cassandra alternative big data database with ultra-low latency and extremely high throughput.
* What it means: Legendary monster who lives on one side of a narrow channel of water, opposite her counterpart Charybdis.

=== Thanos

* Site: https://thanos.io/
* Description: Thanos is a set of components that can be composed into a highly available metric system with unlimited storage capacity, which can be added seamlessly on top of existing Prometheus deployments.
* What it means: Thanos is a Greek masculine given name and surname, a short form of Athanasios meaning 'immortal'.

