= Greek Names in Software Projects
:toc:

This is a repo aimed to keep a list of all the different kinds of software projects whose names have a Greek origin.


== History

The motivation for this came up from the http://www.jhug.gr/[Greek Java User Group] Slack group, where we've been having fun spotting all these software projects in the wild. At some point, I felt it'd be nice to start keeping track...

== The List

=== Agones

* Site: https://github.com/googleforgames/agones
* Description: Agones is a library for hosting, running and scaling dedicated game servers on Kubernetes.
* What it means: Agones, is derived from the Greek word agōn which roughly translates to “contest”, “competition at games” and “gathering”.

=== Android

* Site: https://www.android.com/
* Description: Android is a mobile operating system based on a modified version of the Linux kernel, designed primarily for touchscreen mobile devices
* What it means: Android is coined from the Greek root andr-, "man" (male) and the suffix -oid, "having the form or likeness of".

=== Apollo

* Site: https://www.apollographql.com
* Description: Apollo is the industry-standard GraphQL implementation, providing the data graph layer that connects modern apps to the cloud.
* What it means: Apollo is one of the Olympian deities in classical Greek and Roman religion and Greek and Roman mythology.

=== Aporia

* Site: https://www.aporia.com/
* Description: Aporia is a company dedicated to Machine Learning monitoring
* What it means: Aporia means question or  query 

=== Argo

* Site: https://argoproj.github.io/
* Description: An umbrella project comprised of open source tools for Kubernetes to run workflows, manage clusters, and do GitOps right.
* What it means: Argo was a ship built by Argus, one of the Argonauts, and was used to retrieve the Golden Fleece

=== Artemis

* Site: https://github.com/FORTH-ICS-INSPIRE/artemis
* Description: ARTEMIS is an open-source tool, that implements a defense approach against BGP prefix hijacking attacks. 
* What it means: In Greek mythology and religion, Artemis (/ˈɑːrtɛmɪs/; Greek: Ἄρτεμις) is the goddess of the hunt, the wilderness, wild animals, nature, vegetation, childbirth, the Moon, and chastity.

=== Athena (Project)

* Site: https://en.wikipedia.org/wiki/Project_Athena
* Description: Project Athena was a joint project of MIT, Digital Equipment Corporation, and IBM to produce a campus-wide distributed computing environment for educational use. It was launched in 1983, and research and development ran until June 30, 1991. As of 2020, Athena is still in production use at MIT.
* What it means: The name of the ancient Greek goddess associated with wisdom, handicraft, and warfare. It is also how we Greeks call our capital, even today. "I like Athena" is sure to impress your Greek friends. ;)

=== Axios

* Site: https://github.com/axios/axios
* Description: Promise based HTTP client for the browser and node.js
* What it means: Axios means worthy, suitable, deserving.

=== Boskos

* Site: https://github.com/kubernetes/test-infra/tree/master/boskos
* Description: Boskos is a resource manager service, that handles and manages different kind of resources and transition between different states.
* What it means: Boskos is a sheperd :sheep: in Greek

=== Cassandra

* Site: https://cassandra.apache.org/
* Description: Cassandra is a highly scalable and available distributed database.
* What it means: Priestess of Apollo in Greek mythology cursed to utter true prophecies, but never to be believed.

=== Digma

* Site: https://digma.ai/
* Description: Digma is an IDE plugin for analyzing code runtime data. It enables rapid development in complex projects by linting and detecting issues as they appear, highlighting possible risks in code and providing code change analysis and context
* What it means: sample

=== Exousia

* Site: https://github.com/eclipse-ee4j/exousia
* Description: Exousia is a standalone implementation of https://jakarta.ee/specifications/authorization/2.0/authorization-spec-2.0[Jakarta Authorization].
* What it means: authority, power

=== Faros 

* Site: https://www.faros.ai
* Description: Faros is a value stream analysis platform focused on engineering productivity
* What it means: Lighthouse

=== Fengari 

* Site: https://fengari.io/
* Description: Fengari is the Lua VM written in JavaScript. It uses JavaScript's garbage collector so that interoperability with the DOM is non-leaky.
* What it means: A small rock in space that has served as the inspiration for endless songs, tales, games, poems and epic adventures: the Earth's moon (Φεγγάρι). From the verb φέγγω ("phéngo"), which means "to shine".

=== Gefyra

* Site: https://github.com/gefyrahq/gefyra
* Description: Gefyra is a toolkit written in Python to run a local development infrastructure for Kubernetes. Gefyra runs as a user-space app and controls the local Docker host and Kubernetes via the Kubernetes Python Client.
* What it means: Bridge (Γέφυρα)

=== Helidon

* Site: https://helidon.io/
* Description: Helidon is a collection of Java libraries designed for creating microservices-based applications.
* What it means: Helidon is a Greek word for swallow, a type of bird that according to Wikipedia has “a slender, streamlined body and long pointed wings, which allow great manoeuvrability and ... very efficient flight”. Perfect for darting through the clouds.

=== Hephaestus

* Site: https://github.com/hephaestus-compiler-project/hephaestus
* Description: Hephaestus is a testing framework for validating static typing procedures in compilers. This is done by a combination of program generation and transformation-based compiler testing.
* What it means: Hephaestus is the Greek god of blacksmiths, metalworking, carpenters, craftsmen, artisans, sculptors, metallurgy, fire, and volcanoes.

=== Istio

* Site: https://github.com/istio/istio
* Description: Connect, secure, control, and observe services. https://istio.io
* What it means: Istio is the sail of a sailing boat/vessel.

=== Kairos

* Site: https://github.com/kairos-io/kairos
* Description: The immutable Linux meta-distribution for edge Kubernetes.
* What it means: When everything else fails, and awkward silence seems undefeatable, "Kairos" (i.e. the weather), comes to save the day! Never again will shared elevator rides feel so awkward again! 


=== Kallithea

* Site: https://kallithea-scm.org/
* Description: Kallithea, a free software source code management system supporting two leading version control systems, Mercurial and Git.
* What it means: Usually a name given to areas with a nice view, as it literally translates to good ("kalli") view ("thea")

=== Katafygio

* Site: https://github.com/bpineau/katafygio
* Description: Katafygio discovers Kubernetes objects (deployments, services, ...), and continuously save them as yaml files in a git repository. This provides real time, continuous backups, and keeps detailled changes history.
* What it means: "Katafygio" means refuge or shelter. If your Kubernetes resources are in any kind of danger, katafygio should be the git repo this tool creates where they can be safely stored.

=== Kerberos

* Site: https://web.mit.edu/kerberos/
* Description: Kerberos is a computer-network authentication protocol that works on the basis of tickets to allow nodes communicating over a non-secure network to prove their identity to one another in a secure manner.
* What it means: In Greek mythology, Cerberus (Greek: Κέρβερος Kérberos), often referred to as the hound of Hades, is a multi-headed dog that guards the gates of the Underworld to prevent the dead from leaving.

=== Kiali

* Site: https://www.kiali.io/
* Description: Kiali is an observability console for Istio with service mesh configuration capabilities.
* What it means: Imagine you're holding a pair of binoculars and a car horn suddenly goes off behind you. Yes, you've dropped the binoculars. They're broken in half. Each half is a "kiali". Also, a binocular - but who has "a" binocular these days?

=== Klotho

* Site: https://www.klo.dev/
* Description: Klotho is a new development model focused on microservices and cloud applicaitons
* What it means: https://en.wikipedia.org/wiki/Clotho[Mythological figure]. She is the one of the Three Fates

=== Korifi

* Site: https://github.com/cloudfoundry/korifi
* Description: Cloud Foundry on Kubernetes
* What it means: Korifi means summit (of a mountain). The highest point you can climb.

=== Kryo

* Site: https://github.com/EsotericSoftware/kryo
* Description: Kryo is a fast and efficient binary object graph serialization framework for Java.
* What it means: It is similar to the greek word cryo, meaning icy cold, and related words (cryonics, etc) (source: https://groups.google.com/g/kryo-users/c/E95riwOlb7Y/m/2SwXQOYniaoJ)

=== Kubernetes

* Site: https://kubernetes.io/
* Description: Production-Grade Container Scheduling and Management
* What it means: https://en.wikipedia.org/wiki/Kubernetes[Kubernetes (κυβερνήτης, Greek for "governor", "helmsman" or "captain")]

=== Kyverno

* Site: https://github.com/kyverno/kyverno
* Description: Kyverno is a policy engine designed for Kubernetes. It can validate, mutate, and generate configurations using admission controls and background scans. Kyverno policies are Kubernetes resources and do not require learning a new language. Kyverno is designed to work nicely with tools you already use like kubectl, kustomize, and Git.
* What it means: To govern (verb). Same origin as "Kubernetes" (fun fact: "kyvernetes" would have been a better pronounciation of the greek word behind it). 

=== Odigos
* Site: https://github.com/keyval-dev/odigos
* Description: Odigos is an observability control plane. Start sending traces, metrics and logs to your favourite observability service (such as Datadog, Honeycomb, Grafana, etc) in a few clicks.
* What it means: Odigos means "driver", in Greek. 


=== Paketo

* Site: https://paketo.io
* Description: Modular Buildpacks, written in Go. Paketo Buildpacks provide language runtime support for applications. They leverage the Cloud Native Buildpacks framework to make image builds easy, performant, and secure.
* What it means: Paketo means "package".

=== Peergos

* Site: https://github.com/Peergos/Peergos
* Description: A p2p, secure file storage, social network and application protocol.
* What it means: The name Peergos comes from the Greek word Πύργος (Pyrgos), which means stronghold or tower, but phonetically spelt with the nice connection to being peer-to-peer. Pronunciation: peer-goss (as in gossip).

=== Piraeus

* Site: https://piraeus.io/
* Description: A cloud native datastore for Kubernetes
* What it means:  Is a port city in Greece

=== Portieris

* Site: https://github.com/IBM/portieris
* Description: A Kubernetes Admission Controller for verifying image trust with Notary.
* What it means: Portieris is the bouncer you'd find in a club.

=== Prometheus

* Site: https://github.com/prometheus/prometheus
* Description: The Prometheus monitoring system and time series database. https://prometheus.io/
* What it means: A name from Greek Mythology, of a Titan, who stole the fire from the gods and gave it to humanity. https://en.wikipedia.org/wiki/Prometheus

=== Pyrsia

* Site: https://github.com/pyrsia/pyrsia
* Description: Decentralized Package Repository
* What it means: It is the name of the optical telegraph invented in the 2nd century BCE. https://en.wikipedia.org/wiki/Phryctoria#Phryctoriae_and_Pyrseia

=== Sidero

* Site: https://www.sidero.dev/
* Description: Sidero is Kubernetes bare metal server provisioning and lifecycle management.
* What it means: Sidero means "iron".

=== Sosivio

* Site: https://www.sosiv.io/
* Description: Sosivio is predictive analysis for Kubernetes incidents
* What it means: Sosivio means "lifejacket".

=== Synnefo

* Site: https://www.synnefo.org/
* Description: Synnefo is open source cloud software used to create massively scalable IaaS clouds.
* What it means: Synnefo means "cloud".

=== Scylla

* Site: https://www.scylladb.com/
* Description: Scylla is a drop-in Apache Cassandra alternative big data database with ultra-low latency and extremely high throughput.
* What it means: Legendary monster who lives on one side of a narrow channel of water, opposite her counterpart Charybdis.

=== Timoni

* Site: https://timoni.sh/
* Description: Timoni is a package manager for Kubernetes, powered by https://cuelang.org/[CUE] and inspired by Helm.
* What it means: Timoni is a steering wheel. Not to be confused with **le**moni, which means - unsurprisingly - lemon. 

=== Theseus

* Site: https://github.com/theseus-os/Theseus
* Description: Theseus is a modern OS written from scratch in Rust that explores 𝐢𝐧𝐭𝐫𝐚𝐥𝐢𝐧𝐠𝐮𝐚𝐥 𝐝𝐞𝐬𝐢𝐠𝐧, novel OS structure, and state management. It strives to close the semantic gap between compiler and hardware to maximally leverage the power of language safety, and thus shift OS responsibilities like resource management into the compiler.
* What it means: Theseus is the name of a king and hero from Athens, in ancient Greek Mythology. Theseus was also the name of my late (sigh) dog, but rumours that this Operating System was named after my dog are, as of yet, unconfirmed. 


=== Thanos

* Site: https://thanos.io/
* Description: Thanos is a set of components that can be composed into a highly available metric system with unlimited storage capacity, which can be added seamlessly on top of existing Prometheus deployments.
* What it means: Thanos is a Greek masculine given name and surname, a short form of Athanasios meaning 'immortal'.
