= Greek Names in Software Projects

This is a repo aimed to keep a list of all the different kinds of software projects whose names have a Greek origin. 

== History

The motivation for this came up from the http://www.jhug.gr/[Greek Java User Group] Slack group, where we've been having fun spotting all these software projects in the wild. At some point, I felt it'd be nice to start keeping track... 

== The List


=== Istio 

* Site: https://github.com/istio/istio
* Description: Connect, secure, control, and observe services. https://istio.io
* What it means: Istio is the sail of a sailing boat/vessel.


=== Kallithea 

* Site: https://kallithea-scm.org/
* Description: Kallithea, a free software source code management system supporting two leading version control systems, Mercurial and Git.
* What it means: Usually a name given to areas with a nice view, as it literally translates to good ("kalli") view ("thea")

=== Kiali

* Site: https://www.kiali.io/
* Description: Kiali is an observability console for Istio with service mesh configuration capabilities. 
* What it means: Imagine you're holding a pair of binoculars and a car horn suddenly goes off behind you. Yes, you've dropped the binoculars. They're broken in half. Each half is a "kiali". Also, a binocular - but who has "a" binocular these days?

=== Kubernetes 

* Site: https://kubernetes.io/
* Description: Production-Grade Container Scheduling and Management
* What it means: https://en.wikipedia.org/wiki/Kubernetes[Kubernetes (κυβερνήτης, Greek for "governor", "helmsman" or "captain")]

=== Portieris 

* Site: https://github.com/IBM/portieris
* Description: A Kubernetes Admission Controller for verifying image trust with Notary.
* What it means: Portieris is the bouncer you'd find in a club. 


=== Prometheus 

* Site: https://github.com/prometheus/prometheus
* Description: The Prometheus monitoring system and time series database. https://prometheus.io/
* What it means: A name from Greek Mythology, of a Titan, who stole the fire from the gods and gave it to humanity. https://en.wikipedia.org/wiki/Prometheus

=== Synnefo 

* Site: https://www.synnefo.org/
* Description: Synnefo is open source cloud software used to create massively scalable IaaS clouds.
* What it means: Synnefo means "cloud".


