name: Radicle Sync

# Controls when the workflow will run
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Install radicle-cli
        env:
          RAD_HOME: ${{ github.workspace }}/.radicle
        run: |
          curl --show-error --silent --fail https://radicle.xyz/install | sh
          echo "RAD_HOME=${{ github.workspace }}/.radicle" >> $GITHUB_ENV
          echo "${RAD_HOME}/bin" >> $GITHUB_PATH

      - name: Setup Radicle Identity
        env:
          RAD_PASSPHRASE: ${{ secrets.RADICLE_IDENTITY_PASSPHRASE }}
        run: |          
          echo "Home: $HOME"
          rad --version          
          rad config init --alias "${{ secrets.RADICLE_IDENTITY_ALIAS}}"
          echo "${{ secrets.RADICLE_IDENTITY_PRIVATE_KEY }}" | base64 --decode > ${{ github.workspace }}/.radicle/keys/radicle
          echo "${{ secrets.RADICLE_IDENTITY_PUBLIC_KEY }}" | base64 --decode > ${{ github.workspace }}/.radicle/keys/radicle.pub
          rad auth 
          rad node start
          
          max_retry=30
          counter=0
          until echo '{"command": "sessions"}' | socat - UNIX-CONNECT:${{ github.workspace }}/.radicle/node/control.sock
          do
             sleep 1
             [[ counter -eq $max_retry ]] && echo "Failed" && exit 1
             echo "Waiting for node to start... $counter"
             ((counter++))
          done

      - name: Clone from Radicle
        run: |
          rad clone "${{ secrets.RADICLE_PROJECT_ID }}" --no-confirm
          cd "${{ secrets.RADICLE_PROJECT_NAME }}"
      
      - name: Fetch code from GitHub
        run: |
          export GH_REPO_URL=$( echo ${{ github.repositoryUrl }} \
            | sed -e 's/git:\/\//git@/g' \
            | sed -e 's/github.com\//github.com:/g')

          git remote add github ${GH_REPO_URL}
          git checkout -B ${{ github.ref }}  --track github/${{ github.ref }}
          
      - name: Push to Radicle Network
        run: |
          git push rad ${{ github.ref }}
        
